version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27000:27017
  app:
    depends_on:
      - mongodb
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/jam
    ports:
      - 3300:3000